name: Builder

on:
  push:
    paths: 
     'Lab7_C/**'

jobs:
  build:

    runs-on: Ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          cd Lab1_C/
          make test 
          ./test
          cd ../Lab2_C  
          make test 
          ./test
          cd ../Lab3_C
          make test
          ./test
          cd ../Lab4.1_C
          make test
          ./test
          cd ../Lab4.2_C
          make test
          ./test
          cd ../Lab2.2_C 
          make test 
          ./test
          cd ../Lab5_C
          make test
          cd ../Lab6_C
          make test
          ./test
