name: Builder

on:
  push:

jobs:
  build:

    runs-on: Ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          cd Lab1_C/
          make test 
          ./test
