name: Codecov

on:
  push:
    paths:
    - 'Lab7_C/**'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          make test
          ./test
      - name: Codecov
        run: cd lab7 && export CODECOV_TOKEN="a7addfd9-864e-452d-be28-dff3fda75095" && bash <(curl -s https://codecov.io/bash)
 
