name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          cd Lab7_C/
          make test
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          files: | 
           ./Lab7_C/catalog.c.gcov
